name: Playwright Tests
on:
  pull_request:
    branches: [main, dev]
jobs:
  pull_request_test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm i && npm ci && npm run build
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run test:pr

      - name: Generate Pull Request report
        uses: daun/playwright-report-summary@v3
        with:
          report-file: results.json

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
